# -*- coding: utf-8 -*-
"""matplotlib-exercises.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fJluryT0h4q8IEEh0Mt079n2cxLu4Lpq

# Matplotlib Practice

This notebook offers a set of exercises to different tasks with Matplotlib.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [Matplotlib documentation](https://matplotlib.org/3.1.1/contents.html).

If you're stuck, don't forget, you can always search for a function, for example if you want to create a plot with `plt.subplots()`, search for [`plt.subplots()`](https://www.google.com/search?q=plt.subplots()).
"""

# Commented out IPython magic to ensure Python compatibility.
# Import the pyplot module from matplotlib as plt and make sure 
# plots appear in the notebook using '%matplotlib inline'
# %matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Create a simple plot using plt.plot()
plt.plot()

# Plot a single Python list
plt.plot([1,2,4,5])

# Create two lists, one called X, one called y, each with 5 numbers in them
x = [1,2,3,4,5]
y = [11,22,33,44,55]

# Plot X & y (the lists you've created)
plt.plot(x,y);

"""There's another way to create plots with Matplotlib, it's known as the object-orientated (OO) method. Let's try it."""

# Create a plot using plt.subplots()
fig,ax = plt.subplots()

#Plot data
ax.plot(x,y);

#Customize plot
ax.set(title="Simple plot",
       xlabel="x-axis",
       ylabel="y-axis")

# Create a plot using plt.subplots() and then add X & y on the axes
## already done

"""Now let's try a small matplotlib workflow."""

# Commented out IPython magic to ensure Python compatibility.
# Import and get matplotlib ready
# %matplotlib inline
import matplotlib.pyplot as plt


# Prepare data (create two lists of 5 numbers, X & y)
x = [30,50,70,20,10]
y = [9,40,80,60,3]

# Setup figure and axes using plt.subplots()
fig,ax = plt.subplots()

# Add data (X, y) to axes
ax.plot(x,y)

# Customize plot by adding a title, xlabel and ylabel
ax.set(title="Simple plot 2",
       xlabel="X-axis",
       ylabel="Y-axis");

# Save the plot to file using fig.savefig()
# fig.savefig(/path/simple-plot-2.png)

"""Okay, this is a simple line plot, how about something a little different?

To help us, we'll import NumPy.
"""

# Import NumPy as np
import numpy as np

# Create an array of 100 evenly spaced numbers between 0 and 100 using NumPy and save it to variable X
x = np.linspace(0,10,100)
x[:5]

# Create a plot using plt.subplots() and plot X versus X^2 (X squared)
fig , ax = plt.subplots()
ax.plot(x,x**2);

"""We'll start with scatter plots."""

# Create a scatter plot of X versus the exponential of X (np.exp(X))
plt.scatter(x,np.exp(x));

# Create a scatter plot of X versus np.sin(X)
plt.scatter(x,np.sin(x));

"""How about we try another type of plot? This time let's look at a bar plot. First we'll make some data."""

# Create a Python dictionary of 3 of your favourite foods with 
# The keys of the dictionary should be the food name and the values their price
fav_food = {'Milk':10,
            'Oats':3,
            'Meat':15}
fav_food

# Create a bar graph where the x-axis is the keys of the dictionary
# and the y-axis is the values of the dictionary
fig ,ax = plt.subplots()
ax.bar(fav_food.keys(),fav_food.values())

# Add a title, xlabel and ylabel to the plot
ax.set(title="Favorite foods",
       xlabel="Food",
       ylabel="Price ($)");

# Make the same plot as above, except this time make the bars go horizontal
fig ,ax = plt.subplots()

#In order to make bar horizontal keys and values need to be in a list
ax.barh(list(fav_food.keys()),list(fav_food.values()))

#Customize plot
ax.set(title="Favorite Food",
       xlabel='Price ($)',
       ylabel="Food");

"""
All this food plotting is making me hungry. But we've got a couple of plots to go.

Let's see a histogram."""

# Create a random NumPy array of 1000 normally distributed numbers using NumPy and save it to X
x = np.random.rand(1000)

# Create a histogram plot of X
fig,ax = plt.subplots()
ax.hist(x);

# Create a NumPy array of 1000 random numbers and save it to X
x = np.random.random(1000)
# Create a histogram plot of X
fig,ax = plt.subplots()
ax.hist(x);

"""Notice how the distributions (spread of data) are different. Why do they differ? 

What else can you find out about the normal distribution? 

Can you think of any other kinds of data which may be normally distributed?

These questions aren't directly related to plotting or Matplotlib but they're helpful to think of.

Now let's try make some subplots. A subplot is another name for a figure with multiple plots on it.
"""

# Create an empty subplot with 2 rows and 2 columns (4 subplots total)
fig ,((ax0,ax1),(ax2,ax3)) = plt.subplots(nrows=2,
                                       ncols=2)

"""Notice how the subplot has multiple figures. Now let's add data to each axes."""

# Create the same plot as above with 2 rows and 2 columns and figsize of (10, 5)
fig ,((ax0,ax1),(ax2,ax3)) = plt.subplots(nrows=2,
                                         ncols=2,
                                         figsize=(10,6))

# Plot X versus X/2 on the top left axes
ax0.plot(x,x/2);

# Plot a scatter plot of 10 random numbers on each axis on the top right subplot
ax1.scatter(np.random.random(10),np.random.random(10));

# Plot a bar graph of the favourite food keys and values on the bottom left subplot
ax2.bar(fav_food.keys(),fav_food.values());

# Plot a histogram of 1000 random normally distributed numbers on the bottom right subplot
ax3.hist(np.random.random(1000));

"""Woah. There's a lot going on there.

Now we've seen how to plot with Matplotlib and data directly. Let's practice using Matplotlib to plot with pandas.

First we'll need to import pandas and create a DataFrame work with.
"""

from google.colab import drive
drive.mount('/content/drive')

# Import pandas as pd
import pandas as pd

# Import the '../data/car-sales.csv' into a DataFame called car_sales and view
car_sales = pd.read_csv("/content/drive/MyDrive/machine_learning/data/car-sales.csv")
car_sales

# Try to plot the 'Price' column using the plot() function
car_sales['Price'].plot()

"""Why doesn't it work?

Hint: It's not numeric data.

In the process of turning it to numeric data, let's create another column which adds the total amount of sales and another one which shows what date the car was sold.

Hint: To add a column up cumulatively, look up the cumsum() function. And to create a column of dates, look up the date_range() function.
"""

# Remove the symbols, the final two numbers from the 'Price' column and convert it to numbers
car_sales["Price"] = car_sales["Price"].str.replace('[\$\,\.]',"")
car_sales["Price"] = car_sales["Price"].str[:-2]
car_sales

# Add a column called 'Total Sales' to car_sales which cumulatively adds the 'Price' column
car_sales["Price"] = car_sales["Price"].astype(str).astype(int)#Make price int

car_sales["Total Sales"] = car_sales["Price"].cumsum()

# Add a column called 'Sale Date' which lists a series of successive dates starting from today (your today)
car_sales["Sale Date"] = pd.date_range("1/1/2020",periods=len(car_sales))

# View the car_sales DataFrame
car_sales

"""Now we've got a numeric column (`Total Sales`) and a dates column (`Sale Date`), let's visualize them."""

# Use the plot() function to plot the 'Sale Date' column versus the 'Total Sales' column
car_sales.plot(x='Sale Date',
               y='Total Sales');

# Convert the 'Price' column to the integers
car_sales["Price"] = car_sales["Price"].astype(str).astype(int)

# Create a scatter plot of the 'Odometer (KM)' and 'Price' column using the plot() function
car_sales.plot(x="Odometer (KM)",
               y="Price",
               kind="scatter");

# Create a NumPy array of random numbers of size (10, 4) and save it to X
x = np.random.rand(10,4)

# Turn the NumPy array X into a DataFrame with columns called ['a', 'b', 'c', 'd']
df = pd.DataFrame(x,columns=["a","b","c","d"])

# Create a bar graph of the DataFrame
df.plot(kind="bar")

# Create a bar graph of the 'Make' and 'Odometer (KM)' columns in the car_sales DataFrame
car_sales.plot(x="Make",y="Odometer (KM)",kind="bar");

# Create a histogram of the 'Odometer (KM)' column
car_sales["Odometer (KM)"].plot(kind="hist");

# Create a histogram of the 'Price' column with 20 bins
car_sales["Price"].plot.hist(bins=20);

"""Now we've seen a few examples of plotting directly from DataFrames using the `car_sales` dataset.

Let's try using a different dataset.
"""

# Import "../data/heart-disease.csv" and save it to the variable "heart_disease"
heart_disease = pd.read_csv("/content/drive/MyDrive/machine_learning/data/heart-disease.csv")
heart_disease.head()

# View the first 10 rows of the heart_disease DataFrame
heart_disease[:10]

# Create a histogram of the "age" column with 50 bins
heart_disease["age"].plot.hist(bins=50);

# Call plot.hist() on the heart_disease DataFrame and toggle the
# "subplots" parameter to True
heart_disease.plot.hist(subplots=True);

"""That plot looks pretty squished. Let's change the figsize."""

# Call the same line of code from above except change the "figsize" parameter
# to be (10, 30)
heart_disease.plot.hist(figsize=(10,30),subplots=True);

"""Now let's try comparing two variables versus the target variable.

More specifially we'll see how age and cholesterol combined effect the target in **patients over 50 years old**.

For this next challenge, we're going to be replicating the following plot:

<img src="../images/matplotlib-heart-disease-chol-age-plot.png"/>
"""

# Replicate the above plot in whichever way you see fit

# Note: The method below is only one way of doing it, yours might be
# slightly different

# Create DataFrame with patients over 50 years old
over_50 = heart_disease[heart_disease["age"] > 50]

# Create the plot
fig,ax = plt.subplots(figsize=(10,6))

# Plot the data
scatter = ax.scatter(over_50["age"],
                     over_50["chol"],
                     c=over_50["target"],
                     cmap="winter")

# Customize the plot
ax.set(title="Heart Disease and Cholesterol Levels",
       xlabel="Age",
       ylabel="Cholesterol");
# Add a legend
ax.legend(*scatter.legend_elements(),title="Target")

# Add a meanline
ax.axhline(over_50["chol"].mean(),linestyle="--");

"""Beatiful, now you've created a plot of two different variables, let's change the style."""

# Check what styles are available under plt
plt.style.available

# Change the style to use "seaborn-whitegrid"
plt.style.use("seaborn-whitegrid")

"""Now the style has been changed, we'll replot the same figure from above and see what it looks like.

If you've changed the style correctly, it should look like the following:
<img src="../images/matplotlib-heart-disease-chol-age-plot-seaborn-whitegrid.png"/>

"""

# Reproduce the same figure as above with the "seaborn-whitegrid" style

# Create the plot
fig , ax = plt.subplots(figsize=(10,6))

# Plot the data
scatter = ax.scatter(over_50["age"],
                     over_50["chol"],
                     c=over_50["target"],
                     cmap="winter")

# Customize the plot
ax.set(title="Heart disease and Cholesterol Levels",
       xlabel="Age",
       ylabel="Cholesterol");

# Add a legend
ax.legend(*scatter.legend_elements(),title="Target")

# Add a meanline
ax.axhline(over_50["chol"].mean(),linestyle="--")

"""Wonderful, you've changed the style of the plots and the figure is looking different but the dots aren't a very good colour.

Let's change the `cmap` parameter of `scatter()` as well as the `color` parameter of `axhline()` to fix it.

Completing this step correctly should result in a figure which looks like this:
<img src="../images/matplotlib-heart-disease-chol-age-plot-cmap-change.png"/>
"""

# Replot the same figure as above except change the "cmap" parameter
# of scatter() to "winter"
# Also change the "color" parameter of axhline() to "red"

# Create the plot
fig , ax = plt.subplots(figsize=(10,6))

# Plot the data
scatter = ax.scatter(over_50["age"],
                     over_50["chol"],
                     c=over_50["target"],
                     cmap="winter")

# Customize the plot
ax.set(title="Heart disease and Cholestrol Levels",
       xlabel="Age",
       ylabel="Cholesterol");

# Add a x lim
ax.set_xlim([50,80])
# Add a y lim
ax.set_ylim([100,500])

# Add a legend
ax.legend(*scatter.legend_elements(),title="Target")

# Add a meanline
ax.axhline(over_50["chol"].mean(),
           linestyle="--",
           color="red");

"""Beautiful! Now our figure has an upgraded color scheme let's save it to file."""

# Save the current figure using savefig(), the file name can be anything you want
#fig.savefig("/path/heart-disease-and-chol-levels.png")

# Reset the figure by calling plt.subplots()
fig , ax = plt.subplots()

"""## Extensions

For more exercises, check out the [Matplotlib tutorials page](https://matplotlib.org/3.1.1/tutorials/index.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

The next place you could go is the [Stack Overflow page for the top questions and answers for Matplotlib](https://stackoverflow.com/questions/tagged/matplotlib?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful Matplotlib functions here. Don't forget to play around with the Stack Overflow filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. Always be asking yourself, "is there a better way this data could be visualized so it's easier to understand?"
"""